import type { Exercise, WorkoutRoutine } from '../types/fitness';

// Predefined exercises database (~60 popular exercises)
export const SEED_EXERCISES: Omit<Exercise, 'id' | 'createdAt'>[] = [
  // CARDIO EXERCISES
  {
    name: 'Running (Outdoor)',
    description: 'Outdoor running at moderate pace',
    category: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 10,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=_kGESn8ArrU',
  },
  {
    name: 'Running (Treadmill)',
    description: 'Treadmill running at moderate pace',
    category: 'cardio',
    equipment: ['treadmill'],
    difficulty: 'beginner',
    caloriesPerMinute: 9,
    isCustom: false,
  },
  {
    name: 'Cycling (Outdoor)',
    description: 'Outdoor cycling at moderate intensity',
    category: 'cardio',
    equipment: ['bicycle'],
    difficulty: 'beginner',
    caloriesPerMinute: 8,
    isCustom: false,
  },
  {
    name: 'Cycling (Stationary)',
    description: 'Indoor stationary bike cycling',
    category: 'cardio',
    equipment: ['stationary-bike'],
    difficulty: 'beginner',
    caloriesPerMinute: 7,
    isCustom: false,
  },
  {
    name: 'Jump Rope',
    description: 'Jumping rope for cardio conditioning',
    category: 'cardio',
    equipment: ['jump-rope'],
    difficulty: 'intermediate',
    caloriesPerMinute: 12,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=FJmRQ5iTXKE',
  },
  {
    name: 'Burpees',
    description: 'Full body explosive movement',
    category: 'cardio',
    equipment: ['none'],
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=TU8QYVW0gDU',
  },
  {
    name: 'Mountain Climbers',
    description: 'Core and cardio plank variation',
    category: 'cardio',
    equipment: ['none'],
    difficulty: 'intermediate',
    caloriesPerMinute: 9,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
  },
  {
    name: 'Rowing Machine',
    description: 'Full body rowing cardio',
    category: 'cardio',
    equipment: ['rowing-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 11,
    isCustom: false,
  },
  {
    name: 'Elliptical',
    description: 'Low-impact elliptical cardio',
    category: 'cardio',
    equipment: ['elliptical'],
    difficulty: 'beginner',
    caloriesPerMinute: 8,
    isCustom: false,
  },
  {
    name: 'Swimming',
    description: 'Swimming laps for full body cardio',
    category: 'cardio',
    equipment: ['pool'],
    difficulty: 'intermediate',
    caloriesPerMinute: 11,
    isCustom: false,
  },
  {
    name: 'High Knees',
    description: 'Running in place with high knee raises',
    category: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 8,
    isCustom: false,
  },
  {
    name: 'Box Jumps',
    description: 'Explosive plyometric box jumps',
    category: 'cardio',
    equipment: ['box'],
    difficulty: 'advanced',
    caloriesPerMinute: 10,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=NBY9-kTuHEk',
  },

  // STRENGTH - CHEST
  {
    name: 'Push-ups',
    description: 'Classic bodyweight chest exercise',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
  },
  {
    name: 'Bench Press (Barbell)',
    description: 'Barbell chest press on flat bench',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
  },
  {
    name: 'Bench Press (Dumbbell)',
    description: 'Dumbbell chest press on flat bench',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCustom: false,
  },
  {
    name: 'Incline Bench Press',
    description: 'Upper chest focused bench press',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCustom: false,
  },
  {
    name: 'Chest Flyes',
    description: 'Dumbbell chest isolation exercise',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Dips (Chest)',
    description: 'Bodyweight chest dips',
    category: 'strength',
    muscleGroup: 'Chest',
    equipment: ['dip-bars'],
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCustom: false,
  },

  // STRENGTH - BACK
  {
    name: 'Pull-ups',
    description: 'Bodyweight back pulling exercise',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['pull-up-bar'],
    difficulty: 'intermediate',
    caloriesPerMinute: 8,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
  },
  {
    name: 'Deadlift',
    description: 'King of all exercises - full body compound',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    difficulty: 'advanced',
    caloriesPerMinute: 8,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
  },
  {
    name: 'Bent-Over Row (Barbell)',
    description: 'Barbell row for back thickness',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    caloriesPerMinute: 7,
    isCustom: false,
  },
  {
    name: 'Bent-Over Row (Dumbbell)',
    description: 'Single-arm dumbbell row',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'beginner',
    caloriesPerMinute: 6,
    isCustom: false,
  },
  {
    name: 'Lat Pulldown',
    description: 'Cable lat pulldown for back width',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['cable-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Seated Cable Row',
    description: 'Cable rowing for mid-back',
    category: 'strength',
    muscleGroup: 'Back',
    equipment: ['cable-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
  },

  // STRENGTH - LEGS
  {
    name: 'Squats (Barbell)',
    description: 'King of leg exercises',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    caloriesPerMinute: 8,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
  },
  {
    name: 'Squats (Bodyweight)',
    description: 'Bodyweight squat variation',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Lunges',
    description: 'Walking or stationary lunges',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 6,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
  },
  {
    name: 'Bulgarian Split Squats',
    description: 'Single-leg squat variation',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['bench'],
    difficulty: 'intermediate',
    caloriesPerMinute: 7,
    isCustom: false,
  },
  {
    name: 'Leg Press',
    description: 'Machine leg press',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['leg-press-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 6,
    isCustom: false,
  },
  {
    name: 'Romanian Deadlift',
    description: 'Hamstring focused deadlift variation',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    caloriesPerMinute: 7,
    isCustom: false,
  },
  {
    name: 'Leg Curl',
    description: 'Hamstring isolation exercise',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['leg-curl-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Leg Extension',
    description: 'Quadriceps isolation exercise',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['leg-extension-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Calf Raises',
    description: 'Standing or seated calf raises',
    category: 'strength',
    muscleGroup: 'Legs',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCustom: false,
  },

  // STRENGTH - SHOULDERS
  {
    name: 'Overhead Press (Barbell)',
    description: 'Standing or seated shoulder press',
    category: 'strength',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCustom: false,
  },
  {
    name: 'Overhead Press (Dumbbell)',
    description: 'Dumbbell shoulder press',
    category: 'strength',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Lateral Raises',
    description: 'Side delt isolation exercise',
    category: 'strength',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Front Raises',
    description: 'Front delt isolation exercise',
    category: 'strength',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Face Pulls',
    description: 'Rear delt and upper back exercise',
    category: 'strength',
    muscleGroup: 'Shoulders',
    equipment: ['cable-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },

  // STRENGTH - ARMS
  {
    name: 'Bicep Curls (Barbell)',
    description: 'Classic barbell bicep curl',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['barbell'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Bicep Curls (Dumbbell)',
    description: 'Alternating or simultaneous dumbbell curls',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Hammer Curls',
    description: 'Neutral grip bicep curls',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Tricep Dips',
    description: 'Bodyweight tricep exercise',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['dip-bars'],
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Tricep Pushdown',
    description: 'Cable tricep isolation',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['cable-machine'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Overhead Tricep Extension',
    description: 'Overhead dumbbell or cable tricep exercise',
    category: 'strength',
    muscleGroup: 'Arms',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },

  // STRENGTH - CORE
  {
    name: 'Plank',
    description: 'Isometric core hold',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCustom: false,
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
  },
  {
    name: 'Crunches',
    description: 'Basic abdominal crunches',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Russian Twists',
    description: 'Rotational core exercise',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Bicycle Crunches',
    description: 'Dynamic ab exercise',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCustom: false,
  },
  {
    name: 'Leg Raises',
    description: 'Lower ab focused exercise',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'intermediate',
    caloriesPerMinute: 4,
    isCustom: false,
  },
  {
    name: 'Dead Bug',
    description: 'Core stability exercise',
    category: 'strength',
    muscleGroup: 'Core',
    equipment: ['none'],
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCustom: false,
  },

  // FLEXIBILITY - YOGA
  {
    name: 'Downward Dog',
    description: 'Classic yoga pose for full body stretch',
    category: 'flexibility',
    muscleGroup: 'Full Body',
    equipment: ['yoga-mat'],
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCustom: false,
  },
  {
    name: 'Warrior I',
    description: 'Standing yoga pose for legs and core',
    category: 'flexibility',
    muscleGroup: 'Legs',
    equipment: ['yoga-mat'],
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCustom: false,
  },
  {
    name: 'Warrior II',
    description: 'Standing yoga pose for strength and balance',
    category: 'flexibility',
    muscleGroup: 'Legs',
    equipment: ['yoga-mat'],
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCustom: false,
  },
  {
    name: 'Child\'s Pose',
    description: 'Resting yoga pose for relaxation',
    category: 'flexibility',
    muscleGroup: 'Back',
    equipment: ['yoga-mat'],
    difficulty: 'beginner',
    caloriesPerMinute: 1,
    isCustom: false,
  },
  {
    name: 'Cat-Cow Stretch',
    description: 'Spinal mobility yoga flow',
    category: 'flexibility',
    muscleGroup: 'Back',
    equipment: ['yoga-mat'],
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCustom: false,
  },
  {
    name: 'Pigeon Pose',
    description: 'Hip opening yoga pose',
    category: 'flexibility',
    muscleGroup: 'Legs',
    equipment: ['yoga-mat'],
    difficulty: 'intermediate',
    caloriesPerMinute: 2,
    isCustom: false,
  },

  // SPORT
  {
    name: 'Basketball',
    description: 'Playing basketball',
    category: 'sport',
    equipment: ['basketball', 'court'],
    difficulty: 'intermediate',
    caloriesPerMinute: 9,
    isCustom: false,
  },
  {
    name: 'Soccer',
    description: 'Playing soccer/football',
    category: 'sport',
    equipment: ['soccer-ball', 'field'],
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCustom: false,
  },
  {
    name: 'Tennis',
    description: 'Playing tennis',
    category: 'sport',
    equipment: ['tennis-racket', 'court'],
    difficulty: 'intermediate',
    caloriesPerMinute: 8,
    isCustom: false,
  },
  {
    name: 'Volleyball',
    description: 'Playing volleyball',
    category: 'sport',
    equipment: ['volleyball', 'court'],
    difficulty: 'beginner',
    caloriesPerMinute: 6,
    isCustom: false,
  },
];

// Predefined workout routine templates
export const SEED_ROUTINES: Omit<WorkoutRoutine, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Full Body Beginner',
    description: 'Perfect starter routine for beginners targeting all major muscle groups',
    exercises: [
      { exerciseId: 'squats_bodyweight', order: 1, sets: 3, reps: 12, restBetweenSets: 60 },
      { exerciseId: 'pushups', order: 2, sets: 3, reps: 10, restBetweenSets: 60 },
      { exerciseId: 'dumbbell_row', order: 3, sets: 3, reps: 12, restBetweenSets: 60 },
      { exerciseId: 'plank', order: 4, sets: 3, duration: 30, restBetweenSets: 45 },
      { exerciseId: 'lunges', order: 5, sets: 3, reps: 10, restBetweenSets: 60 },
    ],
    estimatedDuration: 30,
    estimatedCalories: 200,
    isTemplate: true,
  },
  {
    name: 'HIIT 20 Minutes',
    description: 'High-intensity interval training for maximum calorie burn',
    exercises: [
      { exerciseId: 'jump_rope', order: 1, sets: 4, duration: 60, restBetweenSets: 30 },
      { exerciseId: 'burpees', order: 2, sets: 4, reps: 15, restBetweenSets: 30 },
      { exerciseId: 'mountain_climbers', order: 3, sets: 4, duration: 45, restBetweenSets: 30 },
      { exerciseId: 'high_knees', order: 4, sets: 4, duration: 45, restBetweenSets: 30 },
    ],
    estimatedDuration: 20,
    estimatedCalories: 250,
    isTemplate: true,
  },
  {
    name: 'Upper Body Strength',
    description: 'Focused chest, back, shoulders, and arms workout',
    exercises: [
      { exerciseId: 'bench_press', order: 1, sets: 4, reps: 8, restBetweenSets: 90 },
      { exerciseId: 'pullups', order: 2, sets: 3, reps: 8, restBetweenSets: 90 },
      { exerciseId: 'overhead_press', order: 3, sets: 3, reps: 10, restBetweenSets: 75 },
      { exerciseId: 'bicep_curls', order: 4, sets: 3, reps: 12, restBetweenSets: 60 },
      { exerciseId: 'tricep_dips', order: 5, sets: 3, reps: 12, restBetweenSets: 60 },
    ],
    estimatedDuration: 45,
    estimatedCalories: 280,
    isTemplate: true,
  },
  {
    name: 'Leg Day',
    description: 'Complete lower body workout for strength and mass',
    exercises: [
      { exerciseId: 'squats_barbell', order: 1, sets: 4, reps: 8, restBetweenSets: 120 },
      { exerciseId: 'deadlift', order: 2, sets: 4, reps: 6, restBetweenSets: 120 },
      { exerciseId: 'lunges', order: 3, sets: 3, reps: 12, restBetweenSets: 75 },
      { exerciseId: 'leg_curl', order: 4, sets: 3, reps: 12, restBetweenSets: 60 },
      { exerciseId: 'calf_raises', order: 5, sets: 4, reps: 15, restBetweenSets: 45 },
    ],
    estimatedDuration: 50,
    estimatedCalories: 350,
    isTemplate: true,
  },
  {
    name: 'Core Crusher',
    description: 'Intense ab and core workout',
    exercises: [
      { exerciseId: 'plank', order: 1, sets: 3, duration: 60, restBetweenSets: 45 },
      { exerciseId: 'bicycle_crunches', order: 2, sets: 3, reps: 20, restBetweenSets: 45 },
      { exerciseId: 'russian_twists', order: 3, sets: 3, reps: 30, restBetweenSets: 45 },
      { exerciseId: 'leg_raises', order: 4, sets: 3, reps: 15, restBetweenSets: 45 },
      { exerciseId: 'mountain_climbers', order: 5, sets: 3, duration: 45, restBetweenSets: 45 },
    ],
    estimatedDuration: 25,
    estimatedCalories: 150,
    isTemplate: true,
  },
  {
    name: 'Yoga Flow',
    description: 'Relaxing yoga sequence for flexibility and mindfulness',
    exercises: [
      { exerciseId: 'downward_dog', order: 1, sets: 3, duration: 60, restBetweenSets: 30 },
      { exerciseId: 'warrior_i', order: 2, sets: 3, duration: 45, restBetweenSets: 30 },
      { exerciseId: 'warrior_ii', order: 3, sets: 3, duration: 45, restBetweenSets: 30 },
      { exerciseId: 'pigeon_pose', order: 4, sets: 2, duration: 90, restBetweenSets: 30 },
      { exerciseId: 'childs_pose', order: 5, sets: 2, duration: 60, restBetweenSets: 0 },
    ],
    estimatedDuration: 30,
    estimatedCalories: 80,
    isTemplate: true,
  },
];

export function initializeFitnessData(): void {
  if (typeof window === 'undefined') return;

  const userId = localStorage.getItem('current_user_id') || 'default_user';
  const exercisesKey = `exercises_${userId}`;

  // Check if already initialized
  const existingData = localStorage.getItem(exercisesKey);
  if (existingData) {
    console.log('Fitness data already initialized');
    return;
  }

  // Create exercises with IDs
  const exercises: Exercise[] = SEED_EXERCISES.map((ex, index) => ({
    ...ex,
    id: `ex_seed_${index}_${ex.name.toLowerCase().replace(/\s+/g, '_')}`,
    createdAt: new Date(),
  }));

  // Save exercises
  localStorage.setItem(exercisesKey, JSON.stringify(exercises));

  console.log(`Initialized ${exercises.length} exercises`);
}
